CUDA_VISIBLE_DEVICES=1 python src/train_sft.py \
    --model_name_or_path /data/home/yaokj5/dl/models/baichuan-7B \
    --do_train \
    --dataset sft \
    --finetuning_type lora \
    --lora_target W_pack \
    --output_dir ckpt_baichuan_7B \
    --overwrite_cache \
    --per_device_train_batch_size 4 \
    --gradient_accumulation_steps 4 \
    --lr_scheduler_type cosine \
    --logging_steps 10 \
    --save_steps 1000 \
    --learning_rate 5e-5 \
    --num_train_epochs 3.0 \
    --plot_loss \
    --fp16